/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define ADC_BASE_ADDR 0x58026000UL

#define ADC_CR1_REG_OFFSET  0x08UL

#define ADC_CR1_REG_ADDR (ADC_BASE_ADDR+ADC_CR1_REG_OFFSET)

#define RCC_BASE_ADDR 0x58024400UL

#define RCC_C1_OFFSET_ADDR 0x140UL

#define RCC_C1_REG_ADDR (RCC_BASE_ADDR+RCC_C1_OFFSET_ADDR)


int main(void)
{
	uint32_t *pAddrCr1Reg=(uint32_t *) ADC_CR1_REG_ADDR;
	uint32_t *pRccAhb4Enr=(uint32_t *) RCC_C1_REG_ADDR;

	*pRccAhb4Enr |=(1<<24);
	*pAddrCr1Reg |= (1<<4);

    /* Loop forever */
	for(;;);
}
